config/urls.py
from argparse import Namespace
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("<int:pk>", views.RoomDetail.as_view(), name="detail"),
    path("search", views.SearchView.as_view(), name="search"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"> 
    <title>{% block page_title %}{% endblock page_title %} Nbnb</title>
</head>
<body class="text-gray-800">
    <header class="container max-w-full flex items-center justify-between px-8 h-20 border-b" >
        <div class="flex items-center">
            <a class="mr-6" href="{% url 'core:home' %}">
                <img class="w-6" src="{% static 'img/airbnblogo.png' %}"/>
            </a>
            {% block search-bar %}
                <form method="get" action="{% url 'rooms:search' %}">
                    <input class="border py-2 px-1 rounded-lg" name="city" placeholder="Search by City"/>
                </form>
            {% endblock search-bar %}
        </div>
        {% include "partials/nav.html" %}
    </header>
    {% block content %}{% endblock content %}

    {% include "partials/footer.html" %}
</body>
</body>
</html>